jpi_solux:
    resource: "@JPISoluxBundle/Resources/config/routing.yml"
    prefix:   /

jpi_core:
    resource: "@JPICoreBundle/Resources/config/routing.yml"
    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
home:
    path:     /
    defaults: { _controller: "JPISoluxBundle:Home:index" }

jpi_user:
    resource: "@JPIUserBundle/Resources/config/routing.yml"
    prefix: /admin