home_controller:
    resource: "@JPISoluxBundle/Controller/HomeController.php"
    type:     annotation

jpi_solux_caisse_controller:
    resource: "@JPISoluxBundle/Controller/CaisseController.php"
    type:     annotation    

jpi_solux_famille_controller:
    resource: "@JPISoluxBundle/Controller/FamilleController.php"
    prefix:   /parametrage
    type:     annotation
       
jpi_solux_categorie_controller:
    resource: "@JPISoluxBundle/Controller/CategorieController.php"
    prefix:   /parametrage
    type:     annotation
    
jpi_solux_produit_controller:
    resource: "@JPISoluxBundle/Controller/ProduitController.php"
    prefix:   /parametrage
    type:     annotation
    
jpi_solux_montant_max_achat_controller:
    resource: "@JPISoluxBundle/Controller/MontantMaxAchatController.php"
    prefix:   /parametrage
    type:     annotation
    
jpi_solux_taux_participation_controller:
    resource: "@JPISoluxBundle/Controller/TauxParticipationController.php"
    prefix:   /parametrage
    type:     annotation    

jpi_solux_statut_professionnel_controller:
    resource: "@JPISoluxBundle/Controller/StatutProfessionnelController.php"
    prefix:   /parametrage
    type:     annotation    
