services:
#    jpi_solux.example:
#        class: JPI\SoluxBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    jpi_solux.constraint.mma_limite:
        class: JPI\SoluxBundle\Validator\Constraints\MontantMaximumAchatLimiteValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: mma_limite }
            
    jpi_solux.constraint.tx_part_limite:
        class: JPI\SoluxBundle\Validator\Constraints\TauxParticipationLimiteValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: tx_part_limite }
            
    jpi_solux.constraint.achat_taux_participation_famille:
        class: JPI\SoluxBundle\Validator\Constraints\AchatTauxParticipationFamilleValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: achat_taux_participation_famille }

    jpi_solux.constraint.famille_tx_part_existe:
        class: JPI\SoluxBundle\Validator\Constraints\FamilleTauxParticipationExisteValidator
        arguments: ['@doctrine.orm.entity_manager']
        tags:
            - { name: validator.constraint_validator, alias: famille_tx_part_existe }

    jpi_solux.manager.categorie:
        class: JPI\SoluxBundle\Manager\CategorieManager
        arguments: ['@doctrine.orm.entity_manager']
