<?php

namespace JPI\SoluxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FamilleRepository extends EntityRepository
{
	public function getTauxParticipation($id)
	{	
		$lQuery = $this->_em->createQueryBuilder();
		$lQuery->select('b')
			->from($this->_entityName, 'a')
			->from('JPI\SoluxBundle\Entity\TauxParticipation', 'b')
			->where($lQuery->expr()->eq('a.id', ':id'))
			->andWhere($lQuery->expr()->gte($lQuery->expr()->diff('a.recettes', 'a.depenses'), 'b.min'))
			->andWhere($lQuery->expr()->lte($lQuery->expr()->diff('a.recettes', 'a.depenses'), 'b.max'))
			->setParameter('id', $id);

		return $lQuery
			->getQuery()
			->getOneOrNullResult();
	}
}
