<?php

namespace JPI\SoluxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends EntityRepository
{
	public function getProduit($id)
	{
		$lQuery = $this
		->createQueryBuilder('a')
		->where('a.id = :id')
		->setParameter('id', $id)
		->leftJoin('a.limites', 'limites')
		->addSelect('limites')
		->join('a.categorie', 'categorie')
		->addSelect('categorie')
		->orderBy('limites.nbMembreMin', 'ASC');
		
		return $lQuery
		->getQuery()
		->getResult()
		;
	}
}
