<?php

namespace JPI\SoluxBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StatutProfessionnelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatutProfessionnelRepository extends EntityRepository
{
	public function getOrderedQueryBuilder()
	{
		return $this
		->createQueryBuilder('a')
		->orderBy('a.nom', 'ASC')
		;
	}
}
