services:
#    jpi_core.example:
#        class: JPI\CoreBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    jpi_core.doctrine.entity_audit:
        class: JPI\CoreBundle\DoctrineListener\EntityAudit
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: prePersist }
    jpi_core.export:
        class: JPI\CoreBundle\Export\JPIExport
        arguments: ['@phpexcel', '@translator']
